# Generated by Django 4.1.5 on 2023-01-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unidade_de_medida', models.CharField(max_length=20)),
                ('estoque', models.CharField(max_length=20)),
                ('imagem', models.ImageField(upload_to='cars')),
            ],
        ),
    ]
