# Generated by Django 4.1.5 on 2023-01-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='cars'),
        ),
    ]
