# Generated by Django 4.1.5 on 2023-01-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_usuario_cpf_alter_usuario_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
