# Generated by Django 4.2.6 on 2024-01-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_itemcarrinho_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='status',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
